### ISSUE TITLE
Estimate memory usage

### ISSUE THREAD

**Issue by 0xVavaldi** [synacktiv/rulesfinder#11]
I was wondering if it was possible to estimate the maximum memory usage based on the size of the wordlist and target file, or perhaps a general formula we can apply to estimate how much RAM we need to complete an analysis.

In some cases you get returned a result from the OS like ```memory allocation of 420906795024 bytes failed```
But in other cases, no response is returned

**Comment by SimonMarechal** [comment]
It is not obvious how to compute this as it really depends on the dictionary characteristics. If you are using too much memory, it means you are using huge data sources. If that is the case, you should increase the minsize and cutoff parameters.

If you have the allocation error during the first phase, you must increase minsize. If it's during the second phase, cutoff will have more impact.

I can try to run some benches so that memory usage can be estimated, but it depends on the input parameters as well as the characteristics of the dictionary.

**Comment by 0xVavaldi** [comment]
I don't mind having to rent a 2TB RAM VPS from AWS or the likes to run the analysis I'd like, but I'd prefer to know if it's enough to begin with. So to that end a calculation would be nice - which also brings me to another point, being that the memory usage is really high for a relatively small amount of data - any possibility of optimizing memory usage or finding a way to do the calculations in parts on Disk / memmap?

That way large analysis can be performed over a longer period of time without an abhorrent amount of RAM

**Comment by SimonMarechal** [comment]
Indeed, the previous iteration was written in C and used a Makefile in order to reduce memory usage. However, this made everything slower, and so much more annoying to use. It could be possible to dump the retained rules so that only the "fragments" would be kept in memory at a time.

**Comment by SimonMarechal** [comment]
I am pretty sure however that you can fit a good analysis in 128Gb of RAM ^^. An rule set that requires 2TB of RAM might only be 1% better than one that would require 32GB. It also depends on how many rules you want to have in the end. I'll try to work on a performance guide when I have time (which is ... not too soon :( )

**Comment by 0xVavaldi** [comment]
An analysis on 16MB wordlist against 250MB resulted in the errors above requiring more than 400GB of RAM so this is far from a larger analysis. The amount of rules returned shouldn't be too much of a factor here because it crashes before it reaches the end of the first step or the first few of the second step.

In my case my end goal is a 75MB against 12GB comparison

**Comment by SimonMarechal** [comment]
Ah, I'll try to check this with something that has similar metrics!

**Comment by SimonMarechal** [comment]
So, this is indeed impossible ^^ all the cleartexts fragments need to stay in memory in the current version, because the memory overhead is huge. I'll try to see if there are quick wins to have.

**Comment by roycewilliams** [comment]
Naively, is there any benefit in analyzing a single larger corpus, vs cutting the corpus into X pieces and running the rulesfinder X times, etc. ?

**Comment by SimonMarechal** [comment]
Naively, I would expect analyzing a random excerpt of a large corpus to be only slightly less efficient.

The purpose of this tool was to be used during engagements, with a relatively small amount of cleartexts in order to quickly extract the "mannerism" of the target users. Using it with "large" aggregated datasets hasn't really be tested until now ^^

**Comment by SimonMarechal** [comment]
So the I optimized the memory usage for the first size a bit (takes about 35% less memory in my tests). I also remove the strong preallocation that happened by default. You can now try to run with a small part of your corpus, and estimate the memory usage for the first phase as it is mostly proportional!
